import type { ScenarioDefinition } from "@/cases/final-submission/types";
import { endingDefinitions } from "@/cases/final-submission/endings";

export const finalSubmissionScenario: ScenarioDefinition = {
  id: "final-submission",
  title: "Final Submission",
  subtitle: "The assignment went through. But did the network you joined really belong to NYU?",
  courseName: "Media, Culture, and Society",
  fileName: "Final_Assignment.pdf",
  fileSize: "8.6 MB",
  networks: [
    {
      id: "campus-secure",
      name: "nyu",
      signal: 1,
      security: "Authentication required",
      summary: "Verify this device with an NYU NetID.",
      operator: "NYU IT",
      connectionTime: "About 10 sec",
    },
    {
      id: "campus-guest",
      name: "nyuguest",
      signal: 2,
      security: "Guest verification",
      summary: "Use a text-message code for temporary access.",
      operator: "NYU Guest Wireless",
      connectionTime: "About 20 sec",
    },
    {
      id: "campus-free-5g",
      name: "NYU_Free_5G",
      signal: 3,
      security: "Open network",
      summary: "No password required; connect immediately.",
      connectionTime: "Immediate",
    },
    {
      id: "mobile-hotspot",
      name: "Maya's iPhone",
      signal: 3,
      security: "Personal hotspot",
      summary: "Estimated data use: about 10 MB.",
      operator: "Nearby device",
      connectionTime: "About 6 sec",
    },
  ],
  endings: endingDefinitions,
  debrief: {
    clueLabels: {
      "network-details": "Official NYU networks identify an operator; NYU_Free_5G does not.",
      "naming-mismatch": "Official network names are lowercase nyu, nyuguest, or eduroam, without Free or 5G.",
      "portal-address": "The access page uses nyu-access.test rather than an nyu.edu domain.",
      "profile-publisher": "The network profile publisher is shown as Unverified.",
      "login-ignored": "The unknown-device login alert was not reviewed promptly.",
    },
    actionLabels: {
      sessionsRevoked: "Ended the unknown-device session",
      passwordChanged: "Changed the campus account password",
      mfaEnabled: "Enabled multi-factor authentication",
      profileRemoved: "Removed the unverified network profile",
      unsafeNetworkForgotten: "Forgot NYU_Free_5G",
      maliciousMessageDeleted: "Deleted the impersonated message",
      classmatesWarned: "Sent classmates a clear warning",
      itReported: "Filed an incident report with university IT",
    },
    correctPath: [
      "Check the official network names shown in Bobst Library.",
      "Choose nyu, nyuguest, eduroam, or a trusted personal hotspot.",
      "Confirm that the sign-in page is controlled by an nyu.edu domain before entering an NYU NetID.",
      "Do not install a profile from an unverified publisher that changes proxies or certificates.",
      "After an unknown login, end the session first, then remove the profile and notify anyone who may be affected.",
    ],
  },
};
