export const reviewedRehearsals = [
  {
    id: "the-voice-you-know",
    title: "The Voice You Know",
    summary: "A familiar adviser voice asks for an urgent payment change. Decide how to verify it, then deal with what your choice changes.",
    location: "Northbridge University",
    duration: "About 8 minutes",
    href: "/rehearsal",
    testId: "featured-rehearsal",
    icon: "message",
    kicker: "IDENTITY · PAYMENT",
  },
  {
    id: "sharing-scope",
    title: "Sharing Scope",
    summary: "A teammate needs access before a deadline. Choose who can enter and what they can change, then respond if the link travels farther.",
    location: "Northbridge University",
    duration: "About 9 minutes",
    href: "/rehearsal/sharing-scope",
    testId: "rehearsal-sharing-scope",
    icon: "folder",
    kicker: "AUDIENCE · PERMISSION",
  },
  {
    id: "recovery-window",
    title: "Recovery Window",
    summary: "A teammate needs publishing access before a live show. Decide whether a handoff fits the task, then inspect what it changed on the account.",
    location: "Northbridge University",
    duration: "About 9 minutes",
    href: "/rehearsal/recovery-window",
    testId: "rehearsal-recovery-window",
    icon: "key",
    kicker: "RECOVERY · AUTHORITY",
  },
] as const;
